// Données de test pour Supabase en attendant la vraie configuration
// À supprimer quand les vraies clés API seront configurées

export const mockAudits = [
  {
    id: "1a2b3c4d-5e6f-7890-abcd-ef1234567890",
    user_id: "user-123",
    org_id: "org-123",
    email: "contact@example.com",
    url: "https://example.com",
    audit_type: "manual",
    status: "completed",
    webhook_id: "audit_abc123",
    score_global: 85,
    score_performance: 78,
    score_seo: 92,
    score_security: 88,
    score_modern: 75,
    created_at: "2024-01-15T10:30:00Z",
    completed_at: "2024-01-15T10:33:00Z",
    audit_results: JSON.stringify({
      performance: { score: 78, metrics: { lcp: 2.1, fid: 45, cls: 0.15 } },
      seo: { score: 92, issues: ["Missing meta description"] },
      security: { score: 88, issues: ["HTTP redirects"] },
      modern: { score: 75, issues: ["Outdated CSS", "No service worker"] },
    }),
    is_public: false,
    delivery_method: null,
    error_message: null,
  },
  {
    id: "2b3c4d5e-6f78-9012-bcde-f23456789012",
    user_id: "user-123",
    org_id: "org-123",
    email: "info@testsite.com",
    url: "https://testsite.com",
    audit_type: "bulk",
    status: "processing",
    webhook_id: "batch_def456_1",
    score_global: null,
    score_performance: null,
    score_seo: null,
    score_security: null,
    score_modern: null,
    created_at: "2024-01-15T11:15:00Z",
    completed_at: null,
    audit_results: null,
    is_public: false,
    delivery_method: null,
    error_message: null,
  },
  {
    id: "3c4d5e6f-7890-1234-cdef-456789012345",
    user_id: "user-123",
    org_id: "org-123",
    email: "admin@myapp.io",
    url: "https://myapp.io",
    audit_type: "manual",
    status: "failed",
    webhook_id: "audit_ghi789",
    score_global: null,
    score_performance: null,
    score_seo: null,
    score_security: null,
    score_modern: null,
    created_at: "2024-01-15T09:45:00Z",
    completed_at: "2024-01-15T09:48:00Z",
    audit_results: null,
    is_public: false,
    delivery_method: null,
    error_message: "Site inaccessible - timeout après 30 secondes",
  },
  {
    id: "4d5e6f78-9012-3456-def0-123456789abc",
    user_id: "user-123",
    org_id: "org-123",
    email: "support@ecommerce.fr",
    url: "https://ecommerce.fr",
    audit_type: "bulk",
    status: "completed",
    webhook_id: "batch_jkl012_2",
    score_global: 92,
    score_performance: 88,
    score_seo: 95,
    score_security: 94,
    score_modern: 89,
    created_at: "2024-01-14T16:20:00Z",
    completed_at: "2024-01-14T16:24:00Z",
    audit_results: JSON.stringify({
      performance: { score: 88, metrics: { lcp: 1.8, fid: 32, cls: 0.08 } },
      seo: { score: 95, issues: [] },
      security: { score: 94, issues: [] },
      modern: { score: 89, issues: ["Some legacy JS"] },
    }),
    is_public: false,
    delivery_method: null,
    error_message: null,
  },
  {
    id: "5e6f7890-1234-5678-ef01-23456789bcde",
    user_id: "user-123",
    org_id: "org-123",
    email: "hello@startup.tech",
    url: "https://startup.tech",
    audit_type: "manual",
    status: "pending",
    webhook_id: "audit_mno345",
    score_global: null,
    score_performance: null,
    score_seo: null,
    score_security: null,
    score_modern: null,
    created_at: "2024-01-15T12:05:00Z",
    completed_at: null,
    audit_results: null,
    is_public: false,
    delivery_method: null,
    error_message: null,
  },
];

export const mockSubscription = {
  email: "user@example.com",
  quota_used: 15,
  monthly_quota: 50,
  subscription_tier: "pro",
  subscribed: true,
  quota_reset_date: "2024-02-01T00:00:00Z",
  subscription_end: "2024-12-31T23:59:59Z",
  updated_at: "2024-01-15T12:00:00Z",
};

export const mockUser = {
  id: "user-123",
  email: "user@example.com",
  name: "John Doe",
};

export const mockOrg = {
  id: "org-123",
  slug: "test-org",
  name: "Test Organization",
  email: "admin@testorg.com",
};
